[features]
seeds = false
skip-lint = false

[programs.localnet]
autocrat_v0 = "Ctt7cFZM6K7phtRo5NvjycpQju7X6QTSuqNen2ebXiuc"
autocrat_v1 = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
conditional_vault = "4nCk4qKJSJf8pzJadMnr9LubA6Y7Zw3EacsVqH1TwVXH"
clob = "8BnUecJAvKB7zCcwqhMiVWoqKWcw5S6PDCxWWEM2oxWA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/user/.config/solana/id.json"

[scripts]
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/autocratV0.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/clob.ts"
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/conditionalVault.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000

