[features]
seeds = false
skip-lint = false

[programs.localnet]
autocrat_v0 = "GLmTsw5A8DLCThjNgtMBKVDAG8EZYDVMic1pcjhGLiM1"
conditional_vault = "4nCk4qKJSJf8pzJadMnr9LubA6Y7Zw3EacsVqH1TwVXH"
clob = "8BnUecJAvKB7zCcwqhMiVWoqKWcw5S6PDCxWWEM2oxWA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
initialize_vault = "yarn run tsc scripts/initializeVault.ts --esModuleInterop --resolveJsonModule && node scripts/initializeVault.js"
clob = "yarn run tsc scripts/clob.ts --esModuleInterop --resolveJsonModule && node scripts/clob.js && rm scripts/clob.js"
autocrat_v0 = "yarn run ts-node scripts/autocratV0.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
