[features]
seeds = false
skip-lint = false
[programs.localnet]
autocrat = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
conditional_vault = "4SrgFQyrvEYB3GupUaEjoULXCmzHCcAcTffHbpppycip"

[[test.genesis]]
address = "22Y43yTVxuUkoRKdm9thyRhQ3SdgQS7c7kB6UNCiaczD"
program = "./dependencies/clob.so"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/user/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/autocrat.ts"
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/conditionalVault.ts"
